### ISSUE TITLE
Update to active* 7.0 and active_model_attributes 1.6.0

### ISSUE THREAD

**Issue by onyxrev** [IBM-Cloud/smash-the-state#19]
I tried updating the dependencies to `activesupport ~> 7.0` and `activemodel ~> 7.0`  along with `active_model_attributes ~> 1.6.0` 

Interestingly, ActiveModel 7 now produces a singleton class instead of a normal class, so `SmashTheState::Operation::State` then doesn't have `class_eval` or `instance_eval`.

Need to find an alternative way to create a Smash state. There should be an alternative. This ticket is a placeholder to figure this out to enable library updates.

```
  2) SmashTheState::Operation::State self#eval_validation_directives_block clears the validators, evals the block, runs validate
     Failure/Error: s.class_eval(&block)

     NoMethodError:
       undefined method `class_eval' for #<#<Class:0x0000558737a14668>:0x0000558737a1bc88>
     # ./lib/smash_the_state/operation/state.rb:46:in `block in eval_validation_directives_block'
     # ./lib/smash_the_state/operation/state.rb:42:in `tap'
     # ./lib/smash_the_state/operation/state.rb:42:in `eval_validation_directives_block'
     # ./spec/unit/operation/state_spec.rb:85:in `block (3 levels) in <top (required)>'
```

**Comment by alexhemard** [comment]
https://github.com/IBM-Cloud/smash-the-state/pull/17/files#diff-c46d04303e3f460daa8f6360b56a672d3a247ca22cd4f43db277998df9dff5ddR46

@onyxrev Would this address the issue? It looked like it was being called on an instance of an anonymous class which I just assumed was from Ruby 3 upgrade.

**Comment by onyxrev** [comment]
Yeah, that does the trick. Seems like it could be either `class.instance_eval` or `class.class_eval`. I don't think it matters much in this case as it's an anonymous class. I actually like that it's a singleton, too, because the state class is meant to be single-purpose.

**Comment by onyxrev** [comment]
Closing in favor of https://github.com/IBM-Cloud/smash-the-state/pull/17
